sudo: false
dist: bionic

language: go

go: "1.14"

env:
  global: GOFLAGS=-mod=vendor

install:
  - go mod vendor

jobs:
  include:
    - stage: test
      script:
        - make fmt
        - git diff --exit-code
        - make test
    - stage: build
      script:
        - mkdir -p dist
        - export GOOS="linux"
        - export CGO_ENABLED=0
        - export GOARCH="amd64"
        - go build && mv chkbundle "chkbundle-${GOOS}-${GOARCH}"
        - sha1sum chkbundle-* > chkbundle.sum
      deploy:
        provider: releases
        edge: true
        file:
          - "chkbundle-*"
          - "chkbundle.sum"
        on:
          tags: true
